# Comparing arrays

In [1]:
import numpy as np

In [2]:
np_equal_array_one = np.array([1, 2, 3])
np_equal_array_two = np.array([1, 2, 3])
np_equal_array_three = np.array([4, 5, 3])

In [9]:
np.equal(np_equal_array_one, np_equal_array_two)

array([ True,  True,  True])

In [5]:
np.equal(np_equal_array_one, np_equal_array_three)

array([False, False,  True])

In [7]:
np.array_equal(np_equal_array_one, np_equal_array_two)

True

In [8]:
np.array_equal(np_equal_array_one, np_equal_array_three)

False

# Aggregate Functions

In [10]:
np.sum(np_equal_array_one)

6

In [11]:
np.min(np_equal_array_one)

1

In [13]:
np.mean(np_equal_array_one)

2.0

In [14]:
np.median(np_equal_array_one)

2.0

In [18]:
# Correlation of coffecient
np.corrcoef(np_equal_array_one)

1.0

In [20]:
# Standard Deviation
np.std(np_equal_array_one)

0.816496580927726

# Braodcasting

In [21]:
another_mat = np.array([[1,2,3], [3,4,5]])

In [24]:
another_mat + np_equal_array_one

array([[2, 4, 6],
       [4, 6, 8]])

# Concatenating

In [33]:
np.concatenate((np_equal_array_one, np_equal_array_two))

array([1, 2, 3, 1, 2, 3])

In [34]:
np.vstack((np_equal_array_one, np_equal_array_two))

array([[1, 2, 3],
       [1, 2, 3]])

In [35]:
np.hstack((np_equal_array_one, np_equal_array_two))

array([1, 2, 3, 1, 2, 3])

In [36]:
np.column_stack((np_equal_array_one, np_equal_array_two))

array([[1, 1],
       [2, 2],
       [3, 3]])

In [39]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.hsplit(x, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]